site_name: SQA OnBoarding Challenge
site_description: This is a repo corresponding documentation of the SQA OnBoarding challenge for new hires worked by Fabian P.G
repo_url: https://github.com/wizeline/sqa-challenge-fabianportilloglez 
site_author: Fabian Portillo Gonzalez

nav:
    - Home:
      - 'Index': 'index.md'
    - Back End: 
      - 'Requirements': 'Back-End/back-reqs.md'
      - '1.- Teck Stack': 'Back-End/back-tech-stack.md'
      - '2.- Process': 'Back-End/back-process.md'
      - '3.- Results': 'Back-End/back-results.md'
      - 'TODO: Improvements': 'Back-End/back-improv.md'

    - Front End:
      - 'Requirements': 'Front-End/front-reqs.md'
      - '1.- Teck Stack': 'Front-End/front-tech-stack.md'
      - '2.- Process': 'Front-End/front-process.md'
      - '3.- Results': 'Front-End/front-results.md'
      - 'TODO: Improvements': 'Front-End/front-improv.md'

#    - Performance:
#      - 'Requirements': 'Performance/perf-reqs.md'
#      - '1.- Teck Stack': 'Performance/perf-tech-stack.md'
#      - '2.- Process': 'Performance/perf-process.md' 
#      - '3.- Results': 'Performance/perf-results.md' 
#      - 'TODO: Improvements': 'Performance/perf-improv.md'

    - Jenkins Pipeline:
      - 'Sonarqube': 'Jenkins-Pipeline/sonarqube.md'
      - 'Slack Notification': 'Jenkins-Pipeline/slack-notif.md'
      - 'ESlint': 'Jenkins-Pipeline/eslint.md'
      - 'Frontend scripts': 'Jenkins-Pipeline/front-script.md'
      - 'Backend scripts': 'Jenkins-Pipeline/back-script.md'
#  - 'Performance scripts': 'Jenkins-Pipeline/perf-script.md'

    - Business Presentation:
      - 'Test Plan & Strategy': 'Business-Present/test-plan-strat.md'
      - 'QA process': 'Business-Present/qa-process.md'
      - 'Testing types': 'Business-Present/test-types.md'
      - 'Tools description': 'Business-Present/tools-desc.md'
      - 'Diagram': 'Business-Present/diagram.md'
      - 'Demo - video': 'Business-Present/demo.md'

    - Contribute Doc: 
      - 'Installation': 'Contribute-Doc/install-mkdocs.md'
      - 'Contribute': 'Contribute-Doc/contribute-doc.md'
      - 'References': 'Contribute-Doc/mkdocs-refs.md'

    - References:
      - 'References': 'References/refs.md'

# Configurations
theme:
      name: 'material'
      language: 'en'
      palette:
          primary: 'indigo'
          accent: 'indigo'
      font:
          text: 'Roboto'
      favicon: images/favicon.png
      icon:
        repo: fontawesome/brands/git-alt
      feature:
           tabs: true
      features:
        - navigation.tabs
        - navigation.sections
        - search.suggest
        - search.highlight
        - header.autohide
        - toc.autohide
      extra:
        version:
          method: mike

markdown_extensions:
    - attr_list
    - footnotes
    - tables
    - pymdownx.tasklist:
        custom_checkbox: true
        # clickable_checkbox: true

    - admonition
    - codehilite:
        guess_lang: true
    - toc:
          permalink: true

plugins:
  - search