site_name: SQA OnBoarding Challenge
site_description: This is a repo corresponding documentation of the SQA OnBoarding challenge for new hires worked by Fabian P.G
repo_url: https://github.com/wizeline/sqa-challenge-fabianportilloglez 
site_author: Fabian Portillo Gonzalez

nav:
    - Home:
      - 'Index': 'index.md'
    - Back End: 
      - 'Requirements': 'Back-End/back-reqs.md'
      - 'Process': 'Back-End/back-process.md'
    - Front End:
      - 'Requirements': 'Front-End/front-reqs.md'
      - 'Process': 'Front-End/front-process.md'
    - Performance:
      - 'Requirements': 'Performance/perf-reqs.md'
      - 'Process': 'Performance/perf-process.md'
    - SQA Diagram:
      - 'Diagram': 'SQA-Diagram/sqa-diagram.md'
    - Contribute Doc: 
      - 'Installation': 'Contribute-Doc/install-mkdocs.md'
      - 'Contribute': 'Contribute-Doc/contribute-doc.md'
      - 'References': 'Contribute-Doc/mkdocs-refs.md'

# Configurations
theme:
      name: 'material'
      language: 'en'
      palette:
          primary: 'indigo'
          accent: 'indigo'
      font:
          text: 'Roboto'
      favicon: images/favicon.png
      icon:
        repo: fontawesome/brands/git-alt
      feature:
           tabs: true
      features:
        - navigation.tabs
        - navigation.sections
        - search.suggest
        - search.highlight
        - header.autohide
        - toc.autohide
      extra:
        version:
          method: mike

markdown_extensions:
    - attr_list
    - footnotes
    - tables
    - pymdownx.tasklist:
        custom_checkbox: true
        # clickable_checkbox: true

    - admonition
    - codehilite:
        guess_lang: true
    - toc:
          permalink: true

plugins:
  - search

      



